# Usage:
# - Example post-merge workflow for subscription scope.
# - This workflow runs terraform apply after merging to main.
name: Example - Terraform Sub Scope Merge Apply


on:
  workflow_dispatch:

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - terraform/gh-action-examples/deploy-sub-scope/**
#       - .github/workflows/**
#       - .github/actions/**

jobs:
  terraform:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/terraform-deploy-template.yml
    with:
      terraform_working_directory: terraform/gh-action-examples/deploy-sub-scope
      terraform_version: 1.15.5
      tfvars_file: terraform.tfvars
      run_apply: true
      apply_environment_name: terraform-apply

      azure_subscription_id: c33f9068-3058-4127-a12d-d44382efa830

      backend_resource_group_name: rg-common-solutions-tfstate
      backend_storage_account_name: tfstatecommontc7iagly
      backend_subscription_id: c33f9068-3058-4127-a12d-d44382efa830
      backend_container_name: tfstate
      backend_key: common-solutions/gh-action-examples/deploy-sub-scope.tfstate
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
